name: Pipeline Skeleton

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
        
      - name: Build Backend
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/build
        with:
          docker_image: shijakovski/webapp-backend
          docker_image_tag: $GITHUB_SHA
          component_path: ./backend
        
  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'

      - name: Build Frontend        
        if: steps.filter.outputs.frontend == 'true'
        uses: ./.github/actions/build
        with:
          docker_image: shijakovski/webapp-frontend
          docker_image_tag: $GITHUB_SHA
          component_path: ./frontend
    
  deploy-dev:
    name: '[DEV] Deploy BE/FE'
    runs-on: self-hosted
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
      
      - name: Deploy Backend
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/deploy
        with:
          deployment_name: backend-deployment-dev
          pod_name: backend-dev
          docker_image: shijakovski/webapp-backend:$GITHUB_SHA

      - name: Deploy Frontend
        if: steps.filter.outputs.frontend == 'true'
        uses: ./.github/actions/deploy
        with:
          deployment_name: frontend-deployment-dev
          pod_name: frontend-dev
          docker_image: shijakovski/webapp-frontend:$GITHUB_SHA

  testing-dev:
    name: '[DEV] Run API Tests'
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
        
      - name: Run API Tests
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/test
        with:
          test_environment: DEV
      
  deploy-stg:
    name: '[STG] Deploy BE/FE'
    runs-on: self-hosted
    needs: [testing-dev]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
      
      - name: Deploy Backend
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/deploy
        with:
          deployment_name: backend-deployment-stg
          pod_name: backend-stg
          docker_image: shijakovski/webapp-backend:$GITHUB_SHA

      - name: Deploy Frontend
        if: steps.filter.outputs.frontend == 'true'
        uses: ./.github/actions/deploy
        with:
          deployment_name: frontend-deployment-stg
          pod_name: frontend-stg
          docker_image: shijakovski/webapp-frontend:$GITHUB_SHA

  testing-stg:
    name: '[STG] Run API Tests'
    runs-on: self-hosted
    needs: [deploy-stg]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
        
      - name: Run API Tests
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/test
        with:
          test_environment: STG

  deploy-prod:
    name: '[PROD] Deploy BE/FE'
    runs-on: self-hosted
    needs: [testing-stg]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
      
      - name: Deploy Backend
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/deploy
        with:
          deployment_name: backend-deployment-prod
          pod_name: backend-prod
          docker_image: shijakovski/webapp-backend:$GITHUB_SHA

      - name: Deploy Frontend
        if: steps.filter.outputs.frontend == 'true'
        uses: ./.github/actions/deploy
        with:
          deployment_name: frontend-deployment-prod
          pod_name: frontend-prod
          docker_image: shijakovski/webapp-frontend:$GITHUB_SHA

  testing-prod:
    name: '[PROD] Run API Tests'
    runs-on: self-hosted
    needs: [deploy-prod]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
        
      - name: Run API Tests
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/test
        with:
          test_environment: PRD
